/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Dominio.Residuo;
import Dominio.Solicitud;
import Negocio.FabricaNegocio;
import Negocio.IFacadeNegocio;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author Alejandro Galindo
 */
public class frmAsignacion extends javax.swing.JDialog {
    
    private IFacadeNegocio facade;
    private List<Solicitud> solicitudesNoAtendidas;
    
    private static frmAsignacion instance;

    /**
     * Creates new form frmAsignacion
     * @param parent
     * @param modal
     */
    private frmAsignacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(800, 600);
        this.setTitle("Asignación de traslados");
        this.setLocationRelativeTo(parent);
        this.facade = FabricaNegocio.getFachada();
    }
    
    public static frmAsignacion getInstance(java.awt.Frame parent, boolean modal){
        if(instance == null){
            instance = new frmAsignacion(parent, modal);
        }
        instance.actualizar();
        return instance;
    }
    
    private void actualizar(){
        solicitudesNoAtendidas = facade.obtenerListaSolicitudesNoAtendidas();
        renderizarTablas();
        actualizarColumnas();
    }
    
    private void renderizarTablas() {
        vaciarTablas();
        DefaultTableModel modeloTablaSolicitudes = (DefaultTableModel) tablaSolicitudes.getModel();
        Object rowData[] = new Object[3];

        for (int i = 0; i < solicitudesNoAtendidas.size(); i++) {
            rowData[0] = facade.obtenerEmpresaProductora(solicitudesNoAtendidas.get(i).getRFCEmpresa()).getNombreProductora();
            rowData[1] = solicitudesNoAtendidas.get(i).getFecha();
            
            List<Residuo> residuosTransportar = new ArrayList<>();
            for (int j = 0; j < solicitudesNoAtendidas.get(i).getDetalles().size(); j++) {
                residuosTransportar.add(facade.obtenerResiduo(solicitudesNoAtendidas.get(i).getDetalles().get(j).getIDResiduo()));
            }
            
            rowData[2] = residuosTransportar.toString();
            modeloTablaSolicitudes.addRow(rowData);
        }
    }

    private void vaciarTablas() {
        while (tablaSolicitudes.getRowCount() > 0) {
            ((DefaultTableModel) tablaSolicitudes.getModel()).removeRow(0);
        }
    }
    
    private void actualizarColumnas() {
        scroll.getViewport().setBackground(Color.WHITE);
        tablaSolicitudes.getTableHeader().setReorderingAllowed(false);
        tablaSolicitudes.getTableHeader().setResizingAllowed(true);

        Font f = new Font("Seoge UI", Font.BOLD, 15);
        tablaSolicitudes.getTableHeader().setFont(f);
        
        tablaSolicitudes.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (int i = 0; i < tablaSolicitudes.getColumnCount(); i++) {
            DefaultTableColumnModel colModel = (DefaultTableColumnModel) tablaSolicitudes.getColumnModel();
            TableColumn col = colModel.getColumn(i);
            int width = 0;

            TableCellRenderer renderer = col.getHeaderRenderer();
            for (int r = 0; r < tablaSolicitudes.getRowCount(); r++) {
                renderer = tablaSolicitudes.getCellRenderer(r, i);
                Component comp = renderer.getTableCellRendererComponent(tablaSolicitudes, tablaSolicitudes.getValueAt(r, i),
                        false, false, r, i);
                width = Math.max(width, comp.getPreferredSize().width);
            }
            col.setPreferredWidth(width + 20);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        tablaSolicitudes = new javax.swing.JTable();
        asignarEmpresas = new javax.swing.JButton();
        salirBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(122, 235, 122));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Solicitudes no atendidas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaSolicitudes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablaSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Productor", "Fecha solicitada", "Residuos a transportar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaSolicitudes.setRowHeight(32);
        tablaSolicitudes.setRowMargin(2);
        tablaSolicitudes.setSelectionBackground(new java.awt.Color(122, 235, 122));
        scroll.setViewportView(tablaSolicitudes);

        asignarEmpresas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        asignarEmpresas.setText("Asignar Empresas");
        asignarEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarEmpresasActionPerformed(evt);
            }
        });

        salirBoton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        salirBoton.setText("Salir");
        salirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(asignarEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asignarEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBotonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_salirBotonActionPerformed

    private void asignarEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarEmpresasActionPerformed
        int selectedRow = tablaSolicitudes.getSelectedRow();
        if(selectedRow >= 0){
            Solicitud solicitudEnviar = solicitudesNoAtendidas.get(selectedRow);
            frmDetallesAsignacion detallesAsg = frmDetallesAsignacion.getInstance(null, true, solicitudEnviar);
            detallesAsg.setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione una solicitud de la lista", "No se ha seleccionado una solicitud", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_asignarEmpresasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asignarEmpresas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton salirBoton;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tablaSolicitudes;
    // End of variables declaration//GEN-END:variables
}
