/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Dominio.DetallesSolicitud;
import Dominio.EmpresaTransporte;
import Dominio.Solicitud;
import Excepciones.ResiduosException;
import Negocio.FabricaNegocio;
import Negocio.IFacadeNegocio;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alejandro Galindo
 */
public class frmAsignarEmpresas extends javax.swing.JDialog {

    private IFacadeNegocio facade = FabricaNegocio.getFachada();
    private DetallesSolicitud detalles;
    private List<EmpresaTransporte> empresas;
    
    private static frmAsignarEmpresas instance;
    
    /**
     * Creates new form frmAsignarEmpresas
     */
    private frmAsignarEmpresas(java.awt.Frame parent, boolean modal, DetallesSolicitud detalles) {
        super(parent, modal);
        initComponents();
        this.setTitle("Asignación de empresas");
        this.setLocationRelativeTo(null);
    }
    
    public static frmAsignarEmpresas getInstance(java.awt.Frame parent, boolean modal, DetallesSolicitud detalles){
        if(instance == null){
            instance = new frmAsignarEmpresas(parent, modal, detalles);
        }
        instance.detalles = detalles;
        instance.actualizar();
        return instance;
    }
    
    private void actualizar(){
        this.empresas = facade.obtenerListaEmpresasTransporte();
        renderizarTablas();
    }
    
    private void renderizarTablas() {
        vaciarTablas();
        DefaultTableModel modeloTablaSolicitudes = (DefaultTableModel) tablaEmpresasTransporte.getModel();
        Object rowData[] = new Object[1];

        for (int i = 0; i < empresas.size(); i++) {
            rowData[0] = empresas.get(i).getNombreTransporte();
            modeloTablaSolicitudes.addRow(rowData);
        }
    }

    private void vaciarTablas() {
        while (tablaEmpresasTransporte.getRowCount() > 0) {
            ((DefaultTableModel) tablaEmpresasTransporte.getModel()).removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpresasTransporte = new javax.swing.JTable();
        asignarTraslado = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(122, 235, 122));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Asignar Empresas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tablaEmpresasTransporte.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablaEmpresasTransporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Empresa de Transporte"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEmpresasTransporte.setRowHeight(32);
        tablaEmpresasTransporte.setRowMargin(2);
        tablaEmpresasTransporte.setSelectionBackground(new java.awt.Color(122, 235, 122));
        jScrollPane1.setViewportView(tablaEmpresasTransporte);

        asignarTraslado.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        asignarTraslado.setText("Asignar Traslado");
        asignarTraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarTrasladoActionPerformed(evt);
            }
        });

        salir.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        salir.setText("Cancelar");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(asignarTraslado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salir)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asignarTraslado)
                    .addComponent(salir))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_salirActionPerformed

    private void asignarTrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarTrasladoActionPerformed
        int[] selectedRows = tablaEmpresasTransporte.getSelectedRows();
        
        if(selectedRows.length > 0){
            try {
                Solicitud solicitud = facade.obtenerSolicitud(String.valueOf(detalles.getIDSolicitud()));
                float cantidadReparto = detalles.getCantidad() / selectedRows.length;
                detalles.setCantidad(0);
                
                for (int selectedRow : selectedRows) {
                    facade.agregarAsignacion(solicitud.getIDSolicitud(), empresas.get(selectedRow).getCodigoAcceso(), detalles.getIDResiduo(), cantidadReparto, detalles.getMedida());
                }
                JOptionPane.showMessageDialog(this, "Asignaciones realizadas", "Asignaciones terminadas", JOptionPane.PLAIN_MESSAGE);
                this.setVisible(false);
            } catch (ResiduosException residuosException) {
                JOptionPane.showMessageDialog(this, residuosException.getMessage(), "Error al realizar la asignacion", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione una o mas empresas", "No se han seleccionado empresa", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_asignarTrasladoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asignarTraslado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salir;
    private javax.swing.JTable tablaEmpresasTransporte;
    // End of variables declaration//GEN-END:variables
}
