/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Dominio.ElementoQuimico;
import Dominio.EmpresaProductora;
import Dominio.Usuario;
import Excepciones.ResiduosException;
import Negocio.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alejandro Galindo
 */
public class frmRegistroResiduo extends javax.swing.JDialog {

    private IFacadeNegocio facade;
    private Usuario usuario;
    private List<ElementoQuimico> elementosTabla;
    private List<ElementoQuimico> elementosNuevoResiduo;
    
    private static frmRegistroResiduo instance;
    
    private frmRegistroResiduo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(800, 600);
        this.setTitle("Registro de Residuo");
        this.setLocationRelativeTo(parent);
        this.facade = FabricaNegocio.getFachada();
    }
    
    public static frmRegistroResiduo getInstance(java.awt.Frame parent, boolean modal, Usuario usuario){
        if(instance == null){
            instance = new frmRegistroResiduo(parent, modal);
        }
        instance.usuario = usuario;
        instance.actualizar();
        return instance;
    }
    
    private void actualizar(){
        try {
            elementosTabla = new ArrayList<>(facade.obtenerListaElementosQuimicos());
        } catch (ResiduosException e) {
            throw new ResiduosException("No se pudieron obtener los elementos quimicos");
        }
        elementosNuevoResiduo = new ArrayList<>();
        codigoText.setText("");
        nombreText.setText("");
        renderizarTablas();
    }
    
    private void renderizarTablas() {
        vaciarTablas();
        DefaultTableModel modeloTablaElementos = (DefaultTableModel) tablaElementos.getModel();
        Object rowData[] = new Object[1];

        for (int i = 0; i < elementosTabla.size(); i++) {
            rowData[0] = elementosTabla.get(i).getNombreElemento();
            modeloTablaElementos.addRow(rowData);
        }

        DefaultTableModel modeloTablaNuevoResiduo = (DefaultTableModel) tablaNuevosResiduos.getModel();
        for (int i = 0; i < elementosNuevoResiduo.size(); i++) {
            rowData[0] = elementosNuevoResiduo.get(i).getNombreElemento();
            modeloTablaNuevoResiduo.addRow(rowData);
        }
    }

    private void vaciarTablas() {
        while (tablaElementos.getRowCount() > 0) {
            ((DefaultTableModel) tablaElementos.getModel()).removeRow(0);
        }

        while (tablaNuevosResiduos.getRowCount() > 0) {
            ((DefaultTableModel) tablaNuevosResiduos.getModel()).removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        codigoText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nombreText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaElementos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaNuevosResiduos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        agregarElementoNuevoResiduo = new javax.swing.JButton();
        quitarElementoNuevoResiduo = new javax.swing.JButton();
        botonRegistrarResiduo = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Código del residuo");

        codigoText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nombre del residuo");

        nombreText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        tablaElementos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablaElementos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Elemento Quimico"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaElementos.setRowHeight(32);
        tablaElementos.setRowMargin(2);
        tablaElementos.setSelectionBackground(new java.awt.Color(122, 235, 122));
        jScrollPane1.setViewportView(tablaElementos);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Elementos Quimicos");

        tablaNuevosResiduos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablaNuevosResiduos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ElementoQuimico"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaNuevosResiduos.setRowHeight(32);
        tablaNuevosResiduos.setRowMargin(2);
        tablaNuevosResiduos.setSelectionBackground(new java.awt.Color(122, 235, 122));
        jScrollPane2.setViewportView(tablaNuevosResiduos);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Elementos Quimicos del nuevo residuo");

        agregarElementoNuevoResiduo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        agregarElementoNuevoResiduo.setText(">");
        agregarElementoNuevoResiduo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarElementoNuevoResiduoActionPerformed(evt);
            }
        });

        quitarElementoNuevoResiduo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        quitarElementoNuevoResiduo.setText("<");
        quitarElementoNuevoResiduo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarElementoNuevoResiduoActionPerformed(evt);
            }
        });

        botonRegistrarResiduo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonRegistrarResiduo.setText("Registrar");
        botonRegistrarResiduo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarResiduoActionPerformed(evt);
            }
        });

        botonCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(122, 235, 122));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar Residuo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreText)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(agregarElementoNuevoResiduo, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(quitarElementoNuevoResiduo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(botonRegistrarResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(agregarElementoNuevoResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(quitarElementoNuevoResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRegistrarResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarResiduoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarResiduoActionPerformed
        String codigo = codigoText.getText();
        String nombre = nombreText.getText();
        String mensajeComprobacion = "";

        if (codigo.equals("")) {
            mensajeComprobacion += "El campo de codigo esta vacio.\n";
        }

        if (nombre.equals("")) {
            mensajeComprobacion += "El campo de nombre esta vacio.\n";
        }

        if (elementosNuevoResiduo.isEmpty()) {
            mensajeComprobacion += "La lista de elementos del nuevo residuo esta vacia.";
        }

        if (mensajeComprobacion.equals("")) {
            try {
                EmpresaProductora empresa = new EmpresaProductora(usuario.getCodigoAcceso(), usuario.getNombre(), usuario.getTipo(), usuario.getNombre());
                facade.agregarResiduo(codigo, nombre, elementosNuevoResiduo, empresa);
                JOptionPane.showMessageDialog(this, "Residuo agregado con exito", "Residuo Agregado", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            } catch (ResiduosException residuosException) {
                JOptionPane.showMessageDialog(this, residuosException.getMessage(), "Error al agregar residuo", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, mensajeComprobacion, "Error de registro", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_botonRegistrarResiduoActionPerformed

    private void agregarElementoNuevoResiduoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarElementoNuevoResiduoActionPerformed
        if (tablaElementos.getRowCount() > 0) {
            int filaSeleccionada = tablaElementos.getSelectedRow();
            if (filaSeleccionada >= 0) {
                elementosNuevoResiduo.add(elementosTabla.get(filaSeleccionada));
                elementosTabla.remove(filaSeleccionada);
                renderizarTablas();
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione un elemento de la tabla de Elementos");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay elementos en la tabla de Elementos");
        }
    }//GEN-LAST:event_agregarElementoNuevoResiduoActionPerformed

    private void quitarElementoNuevoResiduoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarElementoNuevoResiduoActionPerformed
        if (tablaNuevosResiduos.getRowCount() > 0) {
            int filaSeleccionada = tablaNuevosResiduos.getSelectedRow();
            if (filaSeleccionada >= 0) {
                elementosTabla.add(elementosNuevoResiduo.get(filaSeleccionada));
                elementosNuevoResiduo.remove(filaSeleccionada);
                renderizarTablas();
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione un elemento de la tabla de Elementos del Nuevo Residuo");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Agregue elementos a la tabla del Nuevo Residuo");
        }
    }//GEN-LAST:event_quitarElementoNuevoResiduoActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botonCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarElementoNuevoResiduo;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRegistrarResiduo;
    private javax.swing.JTextField codigoText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombreText;
    private javax.swing.JButton quitarElementoNuevoResiduo;
    private javax.swing.JTable tablaElementos;
    private javax.swing.JTable tablaNuevosResiduos;
    // End of variables declaration//GEN-END:variables
}
