USE [master]
GO

/****** Object:  Database [DB_ResiduosP]    Script Date: 05/19/2019 22:49:24 ******/
CREATE DATABASE [DB_ResiduosP] ON  PRIMARY 
( NAME = N'DB_ResiduosP', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DB_ResiduosP.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DB_ResiduosP_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DB_ResiduosP_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DB_ResiduosP] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_ResiduosP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_ResiduosP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_ResiduosP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_ResiduosP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_ResiduosP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_ResiduosP] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_ResiduosP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_ResiduosP] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DB_ResiduosP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_ResiduosP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_ResiduosP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_ResiduosP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_ResiduosP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_ResiduosP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_ResiduosP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_ResiduosP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_ResiduosP] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DB_ResiduosP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_ResiduosP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_ResiduosP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_ResiduosP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_ResiduosP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_ResiduosP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_ResiduosP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_ResiduosP] SET  READ_WRITE 
GO

ALTER DATABASE [DB_ResiduosP] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DB_ResiduosP] SET  MULTI_USER 
GO

ALTER DATABASE [DB_ResiduosP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_ResiduosP] SET DB_CHAINING OFF 
GO


